### ISSUE TITLE
Usage with buildkit

### ISSUE THREAD

**Issue by Veetaha** [LukeMathWalker/cargo-chef#156]
Docker buildkit added `RUN --mount=type=cache` to docker builds. It looks like with this capability we could just do this:

```Dockerfile
RUN --mount=type=cache,sharing=private,target=/usr/local/cargo/git \
    --mount=type=cache,sharing=private,target=/usr/local/cargo/registry \
    --mount=type=cache,sharing=private,target=/build/target \
    cargo build
```

With this, the `target` directory and cargo registry are preserved between the builds. So... Does it mean `cargo chef` is replaced by this feature? I don't see how it even fits into this particular example 🤔

**Comment by LukeMathWalker** [comment]
That feature can be used to speed up your builds, but the problem remains: how do you build that cache?
You also end up with a Docker build that is no longer self-contained - you are now importing data from the environment.

In a nutshell, I don't think buildkit replaces `cargo-chef`. But you should use it _together_ with `cargo-chef` because, among other things, it makes Docker itself faster 😁
