### ISSUE TITLE
`--locked` support

### ISSUE THREAD

**Issue by rsdy** [LukeMathWalker/cargo-chef#184]
I can see that the `cargo chef cook` command will update my dependencies during build.

Cross-referencing this with the code, I can't see a parameter to force building the dependencies with `--locked`, but I've only had a superficial look.

Would you merge a PR that implements this, or am I missing something fundamental?

**Comment by LukeMathWalker** [comment]
That's not the case - if a `Cargo.lock` is present when `cargo chef prepare` is executed, it will be used when executing `cargo chef cook`. `--locked` is, de facto, the default behaviour here (caching wouldn't really work otherwise, you'd be building something different from what the actual final binary needs in terms of dependencies).

**Comment by rsdy** [comment]
Thanks for the quick response!
